### PR TITLE
Fixes SG issue 2147 changes_feed_limit is not taken into account in s…

### PR DESCRIPTION
**Pull request by tleyden**
…g-replicate configuration

Fixes https://github.com/couchbase/sync_gateway/issues/2147

### CODE REVIEW

**Comment by tleyden** [comment]
@sethrosetter after merging, can you bump https://github.com/couchbase/sync_gateway/blob/master/manifest/default.xml#L88 to point to the latest commit on the [sg-replicate](https://github.com/couchbaselabs/sg-replicate) master branch?

**Comment by tleyden** [comment]
I found one more issue, closing this for now.  Will re-open shortly

**Comment by ddash1** [comment]
@adamcfraser Any planned milestone for this?

**Comment by adamcfraser** [comment]
SG master picks up this commit, and it will be included in the next SG release (1.4).

**Comment by ddash1** [comment]
@adamcfraser thanks!!

**Pull request merged**
